language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: scheul93@gmail.com
  api_key:
    secure: uVIIAA7gRkJSC2i7cC7Mv/pA63GZ4afvzI6HgdJvIL94DHX0GC7MVVNFvYy6mWYXfl7YtCP/8m/FTGUyXg2WRQ2kqWc4kU3KKZgVlRjaxRg0XUrGb9gZaJibdi6hdRy0QblFmFeBCEXz7jNY9R8yFYFekx0TJyqbzs687Sp2usy2SMZHqF7hpbJ5EH3TQCYWulRUSFi92NkfbtRsoD6RxEWsbwTpmz0lwbo6sx5gqDisqM0lgZBwsUYCX93a6gjJLt1v4ASDKgEZMzYYUmiViVduLTDN+0rj0czQHuYWkcJhUkJ1m/lw7HGmBVfwZuTCYKMzj4GhdGKGaXE5Eez+V9GHqGiXKCzRLucnJ1Hth4W3XAnFCnT7dsh+ON56fsFZkEy4aza4WzfLptLmafc/zYgmyHDBwdgjLZk669dPkt398jDY4+k0mPQpBoYoMQ2jXLrh5vwT+lgfNrCXuumACDKqNPEepoBVKLerNB17OkznK2iUKo0+1+VrfRJ2w8onrY6G7Y2t5GqQe5YFW/X4pWMP1oEjGixu5cB31RdaAoIX4Lx51ltBfUJ3UQNnRE8IEvAaFIkjHw7hAlV9m+0pD0hRmzZFvt4OXGI38DXNzJeDEALe3ZAC94kh0qlXK0/3qT/jEBnh7TrgyjM1PVPW1QL53PhDmZQlwb0+o5TqlSU=
  on:
    branch: master
    repo: DEGJS/formMapper
